### ISSUE TITLE
Converter from the old Song Forcer code to the new one?

### ISSUE THREAD

**Issue by Wolfy76700** [TheGag96/pm-hax#3]
I'm currently using in my build an old song forcer which bypasses the My Music menu in order to have custom playlists on stages, but I would be greatly interested in using the new one. Do you think a program that converts the old code into the new one could be possible?

Reference for the old code:
- https://smashboards.com/threads/tracklist-modifier-code-for-pm3-6-and-pm-brawlex.438986/ (Tracklist modifier code)
- https://smashboards.com/threads/stage-expansion-2-0-custom-music.304920/ (Stage-Track dependent song loader)

**Comment by TheGag96** [comment]
Sorry dude, you gotta reenter the data itself in the new tool. I hope you find the tool easy enough to use that it won't be a big deal. Let me know if you have issues!
